name: IllitAuction
version: 1.0.0
main: com.illit.auction.IllitAuctionPlugin
api-version: '1.16'
author: Illit

commands:
  ah:
    description: Открыть аукцион
    usage: /<command>
  illit:
    description: Админ-команды Illit
    usage: /<command>

permissions:
  illit.ah.admin:
    default: op
  illit.ah.use:
    default: true
