name: IllitAuction
version: 1.0.0
main: ru.illit.auction.IllitAuctionPlugin
api-version: "1.20"
author: Illit
depend: [Vault]
commands:
  ah:
    description: Открыть аукцион
    usage: /ah [sell|search|my|ник]
  ahsell:
    description: Выставить лот
    usage: /ah sell <цена> [кол-во]
    aliases: [ah sell]
  ahsearch:
    description: Поиск
    usage: /ah search <текст>
    aliases: [ah search]
  illit:
    description: Админ-команды Illit
    usage: /illit ah reload
permissions:
  illit.ah.admin:
    default: op
